runtime: python310
instance_class: F2

automatic_scaling:
  max_instances: 2
  min_instances: 1  # Mudei para 1 para evitar cold starts
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

env_variables:
  FLASK_APP: "main.py"
  FLASK_ENV: "production"
  GOOGLE_CLOUD_PROJECT: "aerial-acre-455118-a9"

handlers:
- url: /static
  static_dir: static

- url: /message_stream
  script: auto
  secure: always

- url: /.*
  script: auto
  secure: always

entrypoint: gunicorn -b :$PORT main:app --timeout 180 --workers 2 --threads 4 --worker-class gevent
